//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmissionsArgs) DeepCopyInto(out *EmissionsArgs) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	if in.WattTimeUsername != nil {
		in, out := &in.WattTimeUsername, &out.WattTimeUsername
		*out = new(string)
		**out = **in
	}
	if in.WattTimePassword != nil {
		in, out := &in.WattTimePassword, &out.WattTimePassword
		*out = new(string)
		**out = **in
	}
	if in.WattTimeBA != nil {
		in, out := &in.WattTimeBA, &out.WattTimeBA
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmissionsArgs.
func (in *EmissionsArgs) DeepCopy() *EmissionsArgs {
	if in == nil {
		return nil
	}
	out := new(EmissionsArgs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EmissionsArgs) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
