//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	config "github.com/siderolabs/kube-scheduler/apis/config"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*EmissionsArgs)(nil), (*config.EmissionsArgs)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_EmissionsArgs_To_config_EmissionsArgs(a.(*EmissionsArgs), b.(*config.EmissionsArgs), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.EmissionsArgs)(nil), (*EmissionsArgs)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_EmissionsArgs_To_v1alpha1_EmissionsArgs(a.(*config.EmissionsArgs), b.(*EmissionsArgs), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_EmissionsArgs_To_config_EmissionsArgs(in *EmissionsArgs, out *config.EmissionsArgs, s conversion.Scope) error {
	if err := v1.Convert_Pointer_string_To_string(&in.WattTimeUsername, &out.WattTimeUsername, s); err != nil {
		return err
	}
	if err := v1.Convert_Pointer_string_To_string(&in.WattTimePassword, &out.WattTimePassword, s); err != nil {
		return err
	}
	if err := v1.Convert_Pointer_string_To_string(&in.WattTimeBA, &out.WattTimeBA, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_EmissionsArgs_To_config_EmissionsArgs is an autogenerated conversion function.
func Convert_v1alpha1_EmissionsArgs_To_config_EmissionsArgs(in *EmissionsArgs, out *config.EmissionsArgs, s conversion.Scope) error {
	return autoConvert_v1alpha1_EmissionsArgs_To_config_EmissionsArgs(in, out, s)
}

func autoConvert_config_EmissionsArgs_To_v1alpha1_EmissionsArgs(in *config.EmissionsArgs, out *EmissionsArgs, s conversion.Scope) error {
	if err := v1.Convert_string_To_Pointer_string(&in.WattTimeUsername, &out.WattTimeUsername, s); err != nil {
		return err
	}
	if err := v1.Convert_string_To_Pointer_string(&in.WattTimePassword, &out.WattTimePassword, s); err != nil {
		return err
	}
	if err := v1.Convert_string_To_Pointer_string(&in.WattTimeBA, &out.WattTimeBA, s); err != nil {
		return err
	}
	return nil
}

// Convert_config_EmissionsArgs_To_v1alpha1_EmissionsArgs is an autogenerated conversion function.
func Convert_config_EmissionsArgs_To_v1alpha1_EmissionsArgs(in *config.EmissionsArgs, out *EmissionsArgs, s conversion.Scope) error {
	return autoConvert_config_EmissionsArgs_To_v1alpha1_EmissionsArgs(in, out, s)
}
