apiVersion: apps/v1
kind: Deployment
metadata:
  name: high-priority-workload
  labels:
    app: high-priority-workload
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: high-priority-workload
  template:
    metadata:
      labels:
        app: high-priority-workload
    spec:
      schedulerName: kube-scheduler-siderolabs
      priorityClassName: high-priority
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
